# ALL TEXT SOM ANVÄNDS I SPELET
# riktigt smidigt faktiskt

class Text:
    def __init__(self, player, enemy, potential_damage=0, potential_health=0, time=None):
        self.start = "Du står mitt i en gladiatorarena, omgiven av en jublande publik. \nSolens strålar reflekteras på din rustning, och dammet virvlar runt dina fötter. \nDu känner publikens förväntan och adrenalinet pumpar genom dina ådror."
        self.welcome = f"Välkommen till gladiatorspelen, {player.name}! \nDu är en modig krigare som har blivit tillfångatagen och tvingas slåss för ditt liv. \nDu måste överleva alla utmaningar för att vinna friheten. Lycka till!"
        self.battle_begins = "En annan gladiator hoppar in i arenan, redo att möta dig i strid. Publiken håller andan i spänning."
        self.introduce_opponent = f"Du står öga mot öga med {enemy.name}."
        self.animal_appears = "En vild tiger hoppar in i arenan och stirrar på dig med hungriga ögon! Du skiftar fokus från din motståndare till det vilda djuret."
        self.choose = "Välj vad du ska göra härnäst: "
        self.choose_fight = "Välj en motståndare att slåss mot: "
        self.choose_weapon = "Välj ett vapen att använda: "
        self.choose_action = f"Du står öga mot öga med {enemy.name}. Vad vill du göra?"
        self.attack = f"Du attackerar {enemy.name} med {player.inventory["weapon"].name} och gör {potential_damage} skada!"
        self.enemy_attacks = f"{enemy.name} attackerar dig med {enemy.inventory["weapon"].name} och gör {potential_damage} skada!"
        self.attack_skilled = f"Du är skicklig med {player.inventory["weapon"].name} och gör extra skada! | +25% skada"
        self.enemy_attack_skilled = f"{enemy.name} är skicklig med {enemy.inventory["weapon"].name} och gör extra skada! | +25% skada"
        self.defend = f"Du försvarar dig mot {enemy.name}!"
        self.run_success = f"Du lyckades fly från {enemy.name} och överlevde, för nu.\nDu lyckades även återhämta dig med {potential_health} hälsa."
        self.enemy_run_success = f"{enemy.name} lyckades precis slita sig från ditt grepp och fly från striden.\nHan lyckades även återhämta sig med {potential_health} hälsa."
        self.run_fail = f"Du försökte fly från striden men {enemy.name} fångade dig och slog dig till marken.\nDu förlorade {potential_damage} hälsa."
        self.enemy_run_fail = f"{enemy.name} försökte fly från dig men du fångade honom och slog honom till marken.\nHan förlorade {potential_damage} hälsa."
        self.steal_weapon = f"Du stal {enemy.name}s {enemy.inventory["weapon"].name} och slängde iväg {player.inventory["weapon"].name}."
        self.open_box = "Du hittade en låda på marken och öppnade den, publiken spänner sig i förväntan."
        self.enemy_open_box = f"{enemy.name} hittade en låda på marken och öppnade den."
        self.found_weapon = f"Du hittade ett nytt vapen i lådan och bytte ut ditt gamla mot {player.inventory["weapon"].name} ({player.inventory["weapon"].attack} skada)."
        self.skilled = "Du känner dig skickligare och mer fokuserad än någonsin med ditt nya vapen. Du gör nu extra skada i strid."
        self.found_shield = "Du hittade en sköld i lådan och tog upp den."
        self.enemy_found_weapon = f"{enemy.name} hittade ett nytt vapen i lådan och bytte ut sitt gamla mot {enemy.inventory["weapon"].name} ({enemy.inventory["weapon"].attack} skada)."
        self.enemy_skilled = f"{enemy.name} känner sig skickligare och mer fokuserad än någonsin med sitt nya vapen. Han gör nu extra skada i strid."
        self.enemy_found_shield = f"{enemy.name} hittade en sköld i lådan och tog upp den."
        self.protected = f"Du är skyddad av din sköld | -50% skada"
        self.enemy_protected = f"{enemy.name} är skyddad av sin sköld | -50% skada"
        self.defend = f"Du försvarar dig mot {enemy.name} och är nu skyddad mot nästa attack."
        self.enemy_defend = f"{enemy.name} försvarar sig mot dig och är nu skyddad mot nästa attack."
        self.already_protected = "Du är redan skyddad mot nästa attack."
        self.stop_defending = "Du tar ner skölden och är inte längre skyddad."
        self.enemy_stop_defending = f"{enemy.name} tar ner skölden och är inte längre skyddad."
        self.continue_defending = "Du känner dig inte färdig än, du fortsätter att försvara dig."
        self.enemy_continue_defending = f"{enemy.name} fortsätter tålmodigt att försvara sig!"
        self.list_stats = f"{enemy.name} har {enemy.health} hälsa kvar. | {enemy.inventory["weapon"].name} - {enemy.inventory["weapon"].attack * 1.25 if enemy.skilled == True else enemy.inventory["weapon"].attack} skada{" (skicklig)" if enemy.skilled == True else ""}{" [SKÖLD AKTIV]" if enemy.protected == True else ""}\nDu har {player.health} hälsa kvar."
        self.time_remaining = f"Tid kvar: {time}"
        self.time_is_out = "Tiden har gått ut. Publiken får nu rösta på vem som ska vinna!"
        self.emperor = "Det verkar som att kejsaren är närvarande! Han reser sig från sin tron och du väntar förväntansfullt på hans beslut."
        self.win = "Du har klarat av alla utmaningar och vunnit gladiatorspelen. Publiken jublar och kastar blommor och mynt. Du är en hjälte, en legend. Du har överlevt."
        self.loss = "Du har fallit i striden. Publiken skriker och buar. Du har förlorat."
        self.draw = "Det är en oavgjord match. Publiken är besviken och du är utmattad."
        self.draw_emperor = "Kejsaren har bestämt att det är en oavgjord match. Publiken är besviken och du är utmattad."
        self.win_emperor = "Kejsaren har bestämt att du är vinnaren! Publiken jublar och kastar blommor och mynt. Du är en hjälte, en legend. Du har överlevt."
        self.loss_emperor = "Kejsaren har bestämt att du har förlorat. Publiken skriker och buar. Du har fallit i striden."
        self.give_up = "Du ger upp och faller till marken. Du har förlorat."
        self.wrong_error = "Ogiltigt val. Försök igen."
        self.oops = "Oops! Något gick fel. För att åtgärda har kejsaren bestämt att du ska få göra ditt val igen. Lycka till!"
        self.choose_option = "Välj ett alternativ: "
        self.enter = "Tryck på enter för att fortsätta.."