class Text:
    def __init__(self, player, enemy, potential_damage=0, potential_health=0, time=None):
        self.start = "Du står mitt i en gladiatorarena, omgiven av en jublande publik. Solens strålar reflekteras på din rustning, och dammet virvlar runt dina fötter. Du känner publikens förväntan och adrenalinet pumpar genom dina ådror."
        self.win = "Du har klarat av alla utmaningar och vunnit gladiatorspelen. Publiken jublar och kastar blommor och mynt. Du är en hjälte, en legend. Du har överlevt."
        self.loss = "Du har fallit i striden. Publiken skriker och buar. Du har förlorat."
        self.time_is_out = "Tiden har gått ut. Publiken får nu rösta på vem som ska vinna!"
        self.emperor = "Det verkar som att kejsaren är närvarande! Han reser sig från sin tron och du väntar förväntansfullt på hans beslut."
        self.draw = "Det är en oavgjord match. Publiken är besviken och du är utmattad."
        self.draw_emperor = "Kejsaren har bestämt att det är en oavgjord match. Publiken är besviken och du är utmattad."
        self.win_emperor = "Kejsaren har bestämt att du är vinnaren! Publiken jublar och kastar blommor och mynt. Du är en hjälte, en legend. Du har överlevt."
        self.loss_emperor = "Kejsaren har bestämt att du har förlorat. Publiken skriker och buar. Du har fallit i striden."
        self.welcome = f"Välkommen till gladiatorspelen, {player.name}! Du är en modig krigare som har blivit tillfångatagen och tvingas slåss för ditt liv. Du måste överleva alla utmaningar för att vinna friheten. Lycka till!"
        self.battle_begins = "En annan gladiator hoppar in i arenan, redo att möta dig i strid. Publiken håller andan i spänning."
        self.introduce_opponent = f"Du står öga mot öga med {enemy.name}."
        self.choose = "Välj vad du ska göra härnäst: "
        self.choose_fight = "Välj en motståndare att slåss mot: "
        self.choose_weapon = "Välj ett vapen att använda: "
        self.choose_action = f"Du står öga mot öga med {enemy.name}. Vad vill du göra?"
        self.attack = f"Du attackerar {enemy.name} med {player.weapon.name} och gör {player.weapon.attack} skada!"
        self.enemy_attacks = f"{enemy.name} attackerar dig med {enemy.weapon.name} och gör {enemy.weapon.attack} skada!"
        self.defend = f"Du försvarar dig mot {enemy.name}!"
        self.run_success = f"Du lyckades fly från {enemy.name} och överlevde, för nu.\nDu lyckades även återhämta dig med {potential_health} hälsa."
        self.run_fail = f"Du försökte fly från striden men {enemy.name} fångade dig och slog dig till marken.\nDu förlorade {potential_damage} hälsa."
        self.wrong_error = "Ogiltigt val. Försök igen."
        self.choose_option = "Välj ett alternativ: "
        self.list_stats = f"{enemy.name} har {enemy.health} hälsa kvar.\nDu har {player.health} hälsa kvar."
        self.enter = "Tryck på enter för att fortsätta.."
        self.time_remaining = f"Tid kvar: {time}"